# Generated by Django 4.1 on 2022-08-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegInsert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('PasswordConfirmation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
