# Generated by Django 4.1 on 2022-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reginsert',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='reginsert',
            name='PasswordConfirmation',
        ),
        migrations.RemoveField(
            model_name='reginsert',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reginsert',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='reginsert',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='reginsert',
            name='username',
        ),
        migrations.AlterField(
            model_name='reginsert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='reginsert',
            table='register',
        ),
    ]
